### PR TITLE
added SignUp workflow

### PR DESCRIPTION
**Pull request by anelej007**
Hi Oscar,
can you please check my pull request? Please let me know if you get any issues.
- 6 SignUp .tpl files added in folder view
-  SignUp workflow added in routes.py
- Current valid usernames(emails)/ password combinations:
 1. usernames = TeamFin@gtech.edu / passwords = TeamFin007
 2. hisps = ["hitclass@hisp.i3l.gatech.edu","teamFinSpecialist@hisp.i3l.gatech.edu"]
 3. fitBitUsernames = TeamFin /  fitBitPasswords = TeamFin007
 4. Permission page content has to replaced with Ethan's Permission. (replacing content of tag <p></p> in permission.tpl)

Note ** Images has not been included in this submission. They will be part of the next one.

### CODE REVIEW

**Comment by omtinez** [comment]
Can you please resolve conflicts and make another push? I can't merge otherwise.

**Comment by anelej007** [comment]
Sure I will take a look when I get home from work. Did you maybe merged Ethan's changes before mine ? That could caused the issue since I first committed permissions.tpl with "fake" TOS.

**Comment by ethancheung2013** [comment]
Jelena, let me know if you want to discuss my changes.  You can text me
8186677982

**Comment by anelej007** [comment]
Hi Oscar,
I fixed merged issues. You should be good to go now. Can you please merge next time from oldest to newest commit? So code base get merged before its changes. It can save us from possible merge issues. Thank you

**Pull request merged**
